name: Publish releases when new tag
on:
  push:
    tags:
      - v[0-9]+**

jobs:
  package_build:
    name: Build and push to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prep Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install build setuptools twine wheel --user
        continue-on-error: false
      - name: Build source and wheel
        id: build
        run: |
          python -m build --outdir dist/
        continue-on-error: true
      - name: Check the output
        run: |
          python -m twine check --strict dist/*
        continue-on-error: false
      - name: Die on failure
        if: steps.build.outcome != 'success'
        run: exit 1
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.AUTH_TOKEN }}
